// <auto-generated />
namespace Server.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class N_atiAveNoroc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(N_atiAveNoroc));
        
        string IMigrationMetadata.Id
        {
            get { return "201805192250450_N_atiAveNoroc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
